version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "80:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8nSuperSecure456
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://n8n-railway.up.railway.app
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]  # disable sementara
      interval: 10s
      timeout: 5s
      retries: 3
